src/Feature/Blog/code/Controllers/BlogListController.cs
using Blog.Feature.Blog.Models;
using Sitecore.ContentSearch;
using Sitecore.ContentSearch.Linq;
using Sitecore.ContentSearch.Linq.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web.Mvc;

namespace Blog.Feature.Blog.Controllers
{
    public class BlogListController : Controller
    {
        // GET: BlogList
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DoSearch(string searchText)
        {

            var myResults = new SearchResults
            {
                Results = new List<SearchResult>()
            };
            var searchIndex = ContentSearchManager.GetIndex("sitecore_web_index"); // Get the search index
            var searchPredicate = GetSearchPredicate(searchText); // Build the search predicate
            using (var searchContext = searchIndex.CreateSearchContext()) // Get a context of the search index
            {
                //Select * from Sitecore_web_index Where Author="searchText" OR Description="searchText" OR Title="searchText"
                //var searchResults = searchContext.GetQueryable<SearchModel>().Where(searchPredicate); // Search the index for items which match the predicate
                var searchResults = searchContext.GetQueryable<BlogSearchModel>()
                    .Where(x => x.TemplateName == "BlogArticle" && x.ItemName != "Home" && x.ItemName != "__Standard Values" && x.ItemName != "404" && (x.Title.Contains(searchText) || x.Category.Contains(searchText) || x.ShortText.Contains(searchText) || x.LongText.Contains(searchText) || x.Tags.Contains(searchText)));   //LINQ query

                var fullResults = searchResults.GetResults();

                // This is better and will get paged results - page 1 with 10 results per page
                //var pagedResults = searchResults.Page(1, 10).GetResults();
                foreach (var hit in fullResults.Hits)
                {
                    var item_uniqueid = hit.Document.ItemPath;
                    var cutFrom = item_uniqueid.IndexOf("{");
                    var cutTo = item_uniqueid.LastIndexOf("}") + 1;
                    var item_id = item_uniqueid.Substring(cutFrom, cutTo - cutFrom);

                    var item = Sitecore.Context.Database.GetItem(item_id);

                    Sitecore.Data.Fields.ImageField small_image = item.Fields["SmallImage"];
                    Sitecore.Data.Fields.ImageField big_image = item.Fields["BigImage"];
                    Sitecore.Data.Items.MediaItem small_img = new Sitecore.Data.Items.MediaItem(small_image.MediaItem);
                    string small_img_src = Sitecore.StringUtil.EnsurePrefix('/', Sitecore.Resources.Media.MediaManager.GetMediaUrl(small_img));
                    string small_img_alt = small_img.Alt;
                    Sitecore.Data.Items.MediaItem big_img = new Sitecore.Data.Items.MediaItem(big_image.MediaItem);
                    string big_img_src = Sitecore.StringUtil.EnsurePrefix('/', Sitecore.Resources.Media.MediaManager.GetMediaUrl(big_img));
                    string big_img_alt = big_img.Alt;

                    string category = "";
                    Sitecore.Data.Fields.ReferenceField droplinkField = item.Fields["Category"];
                    if (droplinkField != null && droplinkField.TargetItem != null)
                    {
                        Sitecore.Data.Items.Item targetItem = droplinkField.TargetItem; // here targetietm is the value in the Droplink field "Title" 
                        category = targetItem.Name;
                    }
                    List<string> tags = new List<string>();
                    Sitecore.Data.Fields.MultilistField multilistField = item.Fields["Tags"];
                    if (multilistField != null)
                    {
                        foreach (Sitecore.Data.Items.Item tempItem in multilistField.GetItems())
                        {
                            tags.Add(tempItem.Name);
                        }
                    }

                    string item_url = Sitecore.Links.LinkManager.GetItemUrl(item);

                    string read_button = Sitecore.Globalization.Translate.Text("ArticleReadButtonLabel");

                    myResults.Results.Add(new SearchResult
                    {
                        ReadButton = read_button,
                        Tags = tags,
                        LongText = hit.Document.LongText,
                        ShortText = hit.Document.ShortText,
                        BigImageAlt = big_img_alt,
                        BigImage = big_img_src,
                        SmallImageAlt = small_img_alt,
                        SmallImage = small_img_src,
                        PostDate = hit.Document.PostDate.ToString("MMM d, yyyy"),
                        Category = category,
                        Title = hit.Document.Title,
                        ItemPath = item_url,
                    });
                }
                return new JsonResult { JsonRequestBehavior = JsonRequestBehavior.AllowGet, Data = myResults };
            }
        }

        /// <summary>
        /// Search logic
        /// </summary>
        /// <param name="searchText">Search term</param>
        /// <returns>Search predicate object</returns>
        public static Expression<Func<BlogSearchModel, bool>> GetSearchPredicate(string searchText)
        {
            var predicate = PredicateBuilder.True<BlogSearchModel>(); // Items which meet the predicate
                                                                  // Search the whole phrase - LIKE
                                                                  // predicate = predicate.Or(x => x.DispalyName.Like(searchText)).Boost(1.2f);
                                                                  // predicate = predicate.Or(x => x.Description.Like(searchText)).Boost(1.2f);
                                                                  // predicate = predicate.Or(x => x.Title.Like(searchText)).Boost(1.2f);
                                                                  // Search the whole phrase - CONTAINS
            predicate = predicate.Or(x => x.LongText.Contains(searchText)); // .Boost(2.0f);
            predicate = predicate.Or(x => x.ShortText.Contains(searchText)); // .Boost(2.0f);
            predicate = predicate.Or(x => x.Category.Contains(searchText)); // .Boost(2.0f);
            predicate = predicate.Or(x => x.Title.Contains(searchText)); // .Boost(2.0f);
            //Where Author="searchText" OR Description="searchText" OR Title="searchText"
            return predicate;
        }
    }
}

src/Feature/Blog/code/Views/Blog/MainBody.cshtml
@using Sitecore.Data.Items;
@using Sitecore.Mvc

@{
    Item item = Sitecore.Context.Database.GetItem("{50E77F1A-E583-48E1-BAC0-95A644C8ED78}");
    Item[] items = item.Axes.GetDescendants();

    <main role="main" class="container blog-posts" style="max-height: 1000px; overflow-y: auto;">

        <div class="row" id="resultsItem">
            <!-- Begin Repeating Elements Area -->
            @foreach (Item it in items)
            {<!-- Begin Repeating Element -->

                string category = "";
                Sitecore.Data.Fields.ReferenceField droplinkField = it.Fields["Category"];
                if (droplinkField != null && droplinkField.TargetItem != null)
                {
                    Sitecore.Data.Items.Item targetItem = droplinkField.TargetItem; // here targetietm is the value in the Droplink field "Title" 
                    category = targetItem.Name;
                }

                <div class="blog-post-card card col-lg-4 col-md-6">
                    @Html.Sitecore().Field("SmallImage", it)
                    <div class="card-body bg-light">
                        <strong class="d-inline-block mb-2 text-success">@category</strong>
                        <h3 class="card-title">@Html.Sitecore().Field("Title", it)</h3>
                        <div class="mb-1 text-muted">
                            @Html.Sitecore().Field("PostDate", it, new { format = "MMM d, yyyy" })
                        </div>
                        <p>@Html.Sitecore().Field("ShortText", it)</p>
                        @{
                            string url = Sitecore.Links.LinkManager.GetItemUrl(it);
                        }
                        <p class="btn btn-warning btn-block"><a href="@url" style="color: white; text-decoration: none;">@Sitecore.Globalization.Translate.Text("ArticleReadButtonLabel")</a></p>
                    </div>
                </div>
                <!-- End Repeating Element -->
            }
            <!-- End Repeating Elements Area -->
        </div>
    </main>

    <br /> <br />
}

src/Feature/Blog/code/Views/Blog/MainBodyFocused.cshtml
@using System
@using Sitecore.Mvc

@{
    var currentPage = Sitecore.Context.Item;
    Sitecore.Data.Items.Item item = (Sitecore.Data.Items.Item)currentPage;

    string category = "";
    Sitecore.Data.Fields.ReferenceField droplinkField = item.Fields["Category"];
    if (droplinkField != null && droplinkField.TargetItem != null)
    {
        Sitecore.Data.Items.Item targetItem = droplinkField.TargetItem; // here targetietm is the value in the Droplink field "Title" 
        category = targetItem.Name;
    }

    List<string> tags = new List<string>();
    Sitecore.Data.Fields.MultilistField multilistField = item.Fields["Tags"];
    if (multilistField != null)
    {
        foreach (Sitecore.Data.Items.Item tempItem in multilistField.GetItems())
        {
            tags.Add(tempItem.Name);
        }
    }
}

<main role="main" class="container blog-post-detail">
    <div class="row">
        <div class="blog-post-detail-card card col-lg-12">
            @Html.Sitecore().Field("BigImage")
            <div class="card-body bg-light">
                <strong class="d-inline-block mb-2 text-success">@category</strong>
                <h3 class="card-title">@Html.Sitecore().Field("Title")</h3>
                <div class="mb-1 text-muted">@Html.Sitecore().Field("PostDate", new { format = "MMM d, yyyy" })</div>
                @Html.Sitecore().Field("LongText")

                <div class="blog-detail-tag-list">
                    <span class="read-more-heading">Read more: </span>
                    @{ 
                        foreach (string tag in tags)
                        {
                            <a class="btn btn-info" href="#" role="button">@tag</a>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</main>

src/Feature/Blog/code/Views/Blog/NotFoundMainBody.cshtml
@using Sitecore.Mvc

<main role="main" class="container blog-posts" style="max-height: 1000px; overflow-y: auto; color: white !important; text-align: center;">
    <h1>Error: @Html.Sitecore().Field("Title")</h1>
    <br />
    <h2>@Html.Sitecore().Field("ShortText")</h2>
</main>

<br />
<br />

src/Feature/Blog/code/Views/Blog/Search.cshtml
<main role="main" class="container blog-posts">
    <div class="main-search">
        <div class="input-group">
            <input type="text" class="form-control" name="search" id="searchInput" placeholder="@Sitecore.Globalization.Translate.Text("SearchBlogsPlaceholderLabel")" required>
            <div class="input-group-append">
                <button class="favorite styled" type="button" id="searchButton">
                    @Sitecore.Globalization.Translate.Text("SearchBlogsButtonLabel")
                </button>
            </div>
        </div>
    </div>
</main>

<br />
<br />

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script>
		$(document).ready(function () {
			$("#searchButton").click(function (e) {
				// debugger;
				e.preventDefault();
				$.ajax({
					type: "GET",
					datatype: "JSON", url: "@Url.Action("DoSearch", "BlogList")",
					contentType: "application/json",
					data: {
						searchText: $("#searchInput").val()
					},
					success: function (result) {
						var resultText = "";
						$('#resultsItem').text(resultText);
						//$('#resultsItem').append("Results from SOLR index <BR><BR>");
						$(result.Results).each(function (index, item) {
							// each iteration
							var ReadButton = item.ReadButton;
							var Tags = item.Tags;
							var LongText = item.LongText;
							var ShortText = item.ShortText;
							var BigImageAlt = item.BigImageAlt;
							var BigImage = item.BigImage;
							var SmallImageAlt = item.SmallImageAlt;
							var SmallImage = item.SmallImage;
							var PostDate = item.PostDate;
							var Category = item.Category;
							var Title = item.Title;
							var ItemPath = item.ItemPath;

							//resultText += (index + 1) + " - " + Title + "; " + Category + "; " + Date + "; " + ShortText + "; " + LongText + "; " + Tags + "; " + SmallImage + "; " + BigImage + "; " + "<BR><BR>";
                            resultText +=
								"<div class='blog-post-card card col-lg-4 col-md-6'>" +
								"<img src='" + SmallImage + "' alt='" + SmallImageAlt + "' />" +
							"<div class='card-body bg-light'>" +
							"<strong class='d-inline-block mb-2 text-success'>" + Category + "</strong>" +
                                "<h3 class='card-title'>" + Title + "</h3>" +
							"<div class='mb-1 text-muted'>" +
							PostDate +
                                "</div>" +
							"<p>" + ShortText + "</p>" +
							"<p class='btn btn-warning btn-block'><a href='" + ItemPath + "' style='color: white; text-decoration: none;'>" + ReadButton + "</a></p>" +
                                "</div>" +
                                "</div>";
						});
						$('#resultsItem').append(resultText);
					},
					error: function (result) {
						alert('error');
					}
				});
			});
		});
</script>